version: '3'

services:

  wz-user-db:
    image: postgres:latest
    container_name: wz-user-db
    networks:
      - wallet-zen
    environment:
      - POSTGRES_DB=wz-user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  wz-financial-db:
    image: postgres:latest
    container_name: wz-financial-db
    networks:
      - wallet-zen
    environment:
      - POSTGRES_DB=wz-financial-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"      

networks:
  wallet-zen:
    driver: bridge