server.port=8087
server.servlet.context-path=/authuser/
spring.application.name=authuser-service

spring.datasource.url=jdbc:postgresql://db:5432/goldhirsch_docker
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.show_sql=true

