version: '3.7'

services:
  db_finance:
    image: 'postgres:13.1-alpine'
    container_name: db_finance
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=wz_finance
    volumes:
      - ./docker/volume_postgres_finance:/var/lib/postgres
    networks:
      - dock-db
networks:
  dock-db:

