spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/Ismadrade/walletzen-repository}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          search-paths:
            - 'wz-financial-repo*'
            - 'wz-user-repo*'
